# Jekyll configuration

name: Liang-Jun Zhu | 飞天小猪
description: GIS, Watershed modeling, Digital terrain analysis...


# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
port: 5000

# This can be '' to hide the Github nav button
github: 'crazyzlj/'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-75301149-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
# disqus: 'liangjunzhusblog'
comments: true
#permalink: /:year/:month/:title
paginate: 4
paginate_path: "page:num"
#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
syntax_highligher: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    # hard_wrap: false
    # extensions:
      # - autolink
      # - footnotes
      # - smart
    # enable_coderay: true
    # coderay:
       # coderay_line_numbers: nil
gems: ['jekyll-paginate','rouge']
timezone: Asia/Shanghai
#exclude: ['README.md', 'LICENSE']
